### ISSUE TITLE
Link to opensea

### ISSUE THREAD

**Issue by Etheriad** [Etheriad/tropical-cardboard#21]
Include a link to both items on opensea.
https://opensea.io/collection/sodaphones
https://opensea.io/collection/tropical-cardboard-tokens

**Comment by CoryKlish** [comment]
@Etheriad where do you want these links? Do you want them as part of their respective mint sections?

**Comment by Etheriad** [comment]
Yes in the mint section is fine, and then again at the end where we link to the persons own collection.

**Comment by CoryKlish** [comment]
Resolved in #27
