### ISSUE TITLE
Wrap up issues

### ISSUE THREAD

**Issue by Etheriad** [Etheriad/tropical-cardboard#28]
1. flip the first image so the colors flow.
2. Un-fuck the CSS
3. Move the "item supply" table to be under the vending machine, or hidden on mobile.
4. Add Gitbook link

**Comment by CoryKlish** [comment]
> flip the first image so the colors flow.

they are actually different colors:

![image](https://user-images.githubusercontent.com/32180969/233500624-cd3298cf-7b89-4684-8fd0-015eea068b86.png)

I'll need another SVG generated if we want it to flow

**Comment by Etheriad** [comment]
Let's flip it anyway for now.

**Comment by CoryKlish** [comment]
1. ~~flip the first image so the colors flow.~~
2. Un-fuck the CSS
3. ~~Move the "item supply" table to be under the vending machine, or hidden on mobile.~~
4. ~~Add Gitbook link~~
